apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-tic-tac-toe-deployment
    labels:
        app: web
spec:
    replicas: 3
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            labels:
                app: web
        spec:
            containers:
            - name: my-tic-tac-toe
              image: tic-tac-toe-app
              imagePullPolicy: Never
              ports:
              - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
    name: my-tic-tac-toe-service
    labels:
        app: web
spec:
    selector:
        app: web
    type: NodePort
    ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080


  
