pipeline {
    agent { 
        node {
            label 'docker-agent-alpine'
            }
      }
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo "Building..."
                sh '''
                touch requirements.txt
                echo "Created this requirement to test this automated pipeline" > requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
                sh '''
                touch deliverables.txt
                echo "Created this to deliverable to test this automated pipeline" > deliverables.txt
                '''
            }
        }
        stage('Delivery') {
            steps {
                echo 'Delivery...'
                sh '''
                touch logs.txt
                echo "Created this log to say 'Build was successful'" > logs.txt
                '''
            }
        }
    }
}